# -*- coding: utf-8 -*-
"""finviz_news.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYCijzxKXIvFP3Zwx72cS1sdTA2lOSEe
"""

pip install openai

import requests
import csv
import openai
import os
from openai import OpenAI

def fetch_stock_news():
    URL = "https://elite.finviz.com/news_export.ashx?v=3&auth=2ab1c101-1f70-4086-b4bd-37d237a73406" #change for the most updated API token
    response = requests.get(URL)

    if response.status_code == 200:
        with open("export.csv", "wb") as file:
            file.write(response.content)
        print("News data successfully saved to export.csv")
    else:
        print("Failed to fetch news data.")

def analyze_news_article(title, stock):


    # Get the API key from the environment variable
    api_key = os.environ.get("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")

    # Check if the API key is set

    client = OpenAI(api_key="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") # Pass the api_key to the OpenAI client

    response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
            {"role": "system", "content": "You are a financial analyst."},
            {"role": "user", "content": f"Take and analyze the URL: {title}, and create a dashboard for each on what to buy and what to sell {stock}."}
        ]
    )

    print(response.choices[0].message.content)
    recommendation = response.choices[0].message.content.strip()  # Extract the recommendation
    return f"{stock}: {recommendation}"

def process_news_data():
    try:
        with open("export.csv", "r", encoding="utf-8") as file:
            reader = csv.reader(file)
            next(reader)  # Skip the header row

            for row in reader:
                title = row[0]  # Assuming the title is in the first column
                stock = row[1]  # Assuming the stock name/ticker is in the second column
                recommendation = analyze_news_article(title, stock)
                print(f"Title: {title}\nAI Recommendation: {recommendation}\n")
    except FileNotFoundError:
        print("News data file not found. Run fetch_stock_news() first.")

if __name__ == "__main__":
    fetch_stock_news()
    process_news_data()